# Copyright 2021 The OpenEthereum Authors.
# Licensed under the Apache License, Version 2.0.

[workspace]
members = ["crates/*", "tools/*"]
default-members = ["crates/*", "tools/evmrun", "tools/scratchpad"]
